/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MiguelRouteImport } from './routes/miguel'
import { Route as PedroRouteImport } from './routes/pedro'
import { Route as PietroRouteImport } from './routes/pietro'
import { Route as PixRouteImport } from './routes/pix'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MiguelRoute = MiguelRouteImport.update({
  id: '/miguel',
  path: '/miguel',
  getParentRoute: () => rootRouteImport,
} as any)
const PedroRoute = PedroRouteImport.update({
  id: '/pedro',
  path: '/pedro',
  getParentRoute: () => rootRouteImport,
} as any)
const PietroRoute = PietroRouteImport.update({
  id: '/pietro',
  path: '/pietro',
  getParentRoute: () => rootRouteImport,
} as any)
const PixRoute = PixRouteImport.update({
  id: '/pix',
  path: '/pix',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/miguel': typeof MiguelRoute
  '/pedro': typeof PedroRoute
  '/pietro': typeof PietroRoute
  '/pix': typeof PixRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/miguel': typeof MiguelRoute
  '/pedro': typeof PedroRoute
  '/pietro': typeof PietroRoute
  '/pix': typeof PixRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/miguel': typeof MiguelRoute
  '/pedro': typeof PedroRoute
  '/pietro': typeof PietroRoute
  '/pix': typeof PixRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/miguel' | '/pedro' | '/pietro' | '/pix'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/miguel' | '/pedro' | '/pietro' | '/pix'
  id: '__root__' | '/' | '/miguel' | '/pedro' | '/pietro' | '/pix'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MiguelRoute: typeof MiguelRoute
  PedroRoute: typeof PedroRoute
  PietroRoute: typeof PietroRoute
  PixRoute: typeof PixRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miguel': {
      id: '/miguel'
      path: '/miguel'
      fullPath: '/miguel'
      preLoaderRoute: typeof MiguelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedro': {
      id: '/pedro'
      path: '/pedro'
      fullPath: '/pedro'
      preLoaderRoute: typeof PedroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pietro': {
      id: '/pietro'
      path: '/pietro'
      fullPath: '/pietro'
      preLoaderRoute: typeof PietroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pix': {
      id: '/pix'
      path: '/pix'
      fullPath: '/pix'
      preLoaderRoute: typeof PixRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MiguelRoute: MiguelRoute,
  PedroRoute: PedroRoute,
  PietroRoute: PietroRoute,
  PixRoute: PixRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
